# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShExpJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=50)),
                ('imgcov', models.FileField(upload_to=b'')),
                ('biref', models.TextField()),
                ('trend', models.TextField()),
                ('catagory', models.TextField()),
                ('department', models.TextField()),
                ('iceberg', models.FileField(upload_to=b'')),
                ('basicskill', models.FileField(upload_to=b'')),
                ('coop', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShExpMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('imgdis', models.FileField(upload_to=b'')),
                ('imgcov', models.FileField(upload_to=b'')),
                ('intro', models.TextField()),
                ('t3', models.TextField()),
                ('trend', models.TextField()),
                ('turnback', models.TextField()),
                ('know10', models.TextField()),
                ('share', models.TextField()),
                ('lifestyle', models.TextField()),
                ('job5', models.TextField()),
                ('pro4', models.TextField()),
                ('date', models.DateTimeField()),
                ('career_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ShExpJob')),
            ],
        ),
    ]
