# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20171001_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shexpjob',
            old_name='catagory',
            new_name='category',
        ),
    ]
